ALTER TABLE BOUNDS DROP CONSTRAINT FK_BOUNDS_CITY_ID
ALTER TABLE COORDINATES DROP CONSTRAINT FK_COORDINATES_BOUNDS_ID
ALTER TABLE LOCATION DROP CONSTRAINT FK_LOCATION_CITY_ID
DROP TABLE CITY
DROP TABLE BOUNDS
DROP TABLE COORDINATES
DROP TABLE LOCATION
DELETE FROM SEQUENCE WHERE SEQ_NAME = 'SEQ_GEN'
